name: pnpm
description: 'Setup node & pnpm'

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 9.15.9
        run_install: true
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://registry.npmjs.org'
        cache: pnpm
